import { Button, VerticalBox, StandardListView, HorizontalBox, Palette, StyleMetrics } from "std-widgets.slint";
import { MainMenu } from "main-menu.slint";
import { RadioBox, AddFolderDialog } from "../widgets/widgets.slint";

component ModalDialogLayer inherits Window {
    visible: false;
    Rectangle {
        opacity: 0.9;
        background: Palette.background;
    }
    VerticalBox {
        alignment: center;
        x: 5% * root.width;
        width: 90% * root.width;
        min-height: 100px;

        dialog_add_folder := AddFolderDialog { 
            cancel => { close-modal(); } 
        } 
    }

    function close-modal() {
        self.visible = false;

        dialog_add_folder.visible = false;
    }

    public function show-add-folder() {
        self.visible = true; 

        dialog_add_folder.show();
    }
}

export component AppWindow inherits Window {
    title: "Gesture Training";
    Rectangle {
        background: Palette.alternate-background;
    }
    MainMenu {
        show-add-folder => { layer_modal.show-add-folder(); }
    } 
    layer_modal := ModalDialogLayer {
        width: root.width;
        height: root.height;
    }
}