import { Palette, StyleMetrics, VerticalBox, HorizontalBox, Switch, ListView } from "std-widgets.slint";
import { RadioBox, Label, Icons, CustomPalette, Button } from "../widgets/widgets.slint";

export struct SourceData {
    enabled: bool,
    name: string,
    image_count: int,
    is_valid: bool,
}

component SourceView inherits Rectangle {
    callback open-editor <=> open_editor_button.clicked;

    in-out property<SourceData> data;

    height: CustomPalette.preferred-field-height;
    background: Palette.control-background;
    border-width: CustomPalette.border-width;
    border-color: Palette.background;

    HorizontalBox {
        padding-left: CustomPalette.border * 2;
        padding-right: 0;
        padding-top: 0;
        padding-bottom: 0;

        Switch {
            enabled: data.enabled;
        }
        text := Text {
            text: data.name;
            vertical-alignment: center;
            horizontal-alignment: left;
        }
        image_count := Text {
            vertical-alignment: center;
            horizontal-alignment: right;
            width: 50px;
            text: data.image_count;
        }
        Rectangle {
            width: CustomPalette.preferred-icon-size;
            Image {
                width: CustomPalette.preferred-icon-size * 0.75;
                source: data.is_valid ? Icons.check-circle : Icons.alert-triangle;
                colorize: data.is_valid ? Palette.foreground : yellow;
            }
        }
        open_editor_button := Button {
            icon: Icons.more-horizontal-square;
            border-radius: 0;
            width: 50px;
        }
    }
}

component MainMenuForm inherits VerticalBox {
    callback show-add-folder <=> button_add_folder.clicked;
    callback open-source-editor(SourceData, int);

    in property<int> total_image_count:0;

    in-out property<[SourceData]> datas : [
        { enabled: true, name: "Clothed misc", image_count: 264, is_valid: true },
        { enabled: true, name: "Chaaron", image_count: 513 },
    ];

    VerticalBox {
        spacing: 0;

        Rectangle {
            height: CustomPalette.preferred-field-height;
            background: Palette.control-background;
            border-top-left-radius: CustomPalette.border;
            border-top-right-radius: CustomPalette.border;
            border-width: CustomPalette.border-width;
            border-color: Palette.background;

            Text {
                text: "Image sources";
            }
        }
        for data[index] in datas: SourceView {
            data: data;
            open-editor => {
                open-source-editor(data, index);
            }
        }
        HorizontalBox {
            spacing: 0;
            padding: 0;

            Rectangle {
                width: CustomPalette.preferred-field-label-width;
                background: Palette.control-background;
                border-width: CustomPalette.border-width;
                border-bottom-left-radius: CustomPalette.border;
                border-color: Palette.background;
    
                Text {
                    width: 100%;
                    x: CustomPalette.border * 2;
                    horizontal-alignment: left;
                    text: "Add Images";
                }
            }

            button_add_folder := Button {
                border-radius: 0;

                icon: Icons.folder;
                colorize-icon: true;
                height: CustomPalette.preferred-field-height;
            }
            button_add_zip := Button {
                border-top-left-radius: 0;
                border-top-right-radius: 0;
                border-bottom-left-radius: 0;

                icon: Icons.zip-file;
                colorize-icon: true;
                height: CustomPalette.preferred-field-height;
            }
        }
        
    }
    
    VerticalBox {
        spacing: 0;

        HorizontalBox {
            spacing: 0;
            padding: 0;
    
            Rectangle {
                width: CustomPalette.preferred-field-label-width;
                background: Palette.control-background;
                border-width: CustomPalette.border-width;
                border-top-left-radius: CustomPalette.border;
                border-color: Palette.background;
    
                Text {
                    width: 100%;
                    x: CustomPalette.border * 2;
                    horizontal-alignment: left;
                    text: "Images";
                }
            }
            RadioBox {
                border-top-right: true;
                height: CustomPalette.preferred-field-height;
                selected-value: 5;
                datas: [
                    {value: 5, display: "5"},
                    {value: 10, display: "10"},
                    {value: 15, display: "15"},
                    {value: 20, display: "20"},
                    {value: 25, display: "25"},
                ];
            }
        }
        HorizontalBox {
            spacing: 0;
            padding: 0;
    
            Rectangle {
                width: CustomPalette.preferred-field-label-width;
                background: Palette.control-background;
                border-width: CustomPalette.border-width;
                border-bottom-left-radius: CustomPalette.border;
                border-color: Palette.background;
    
                Text {
                    width: 100%;
                    x: CustomPalette.border * 2;
                    horizontal-alignment: left;
                    text: "Duration";
                }
            }
            RadioBox {
                border-bottom-right: true;
                height: CustomPalette.preferred-field-height;
                selected-value: 30;
                datas: [
                    {value: 30, display: "30''"},
                    {value: 60, display: "1'"},
                    {value: 120, display: "2'"},
                    {value: 180, display: "3'"}, 
                    {value: 300, display: "5'"}, 
                    {value: 600, display: "10'"}, 
                    {value: 1200, display: "20'"}, 
                ]; 
            }
        }
    }
    
    HorizontalBox {
        height: CustomPalette.preferred-field-height;

        Button {
            text: "Start (" + total_image_count + ")";
        }
    }
}

export component MainMenu inherits Rectangle {
    callback show-add-folder <=> form.show-add-folder;
    callback open-source-editor <=> form.open-source-editor;

    HorizontalBox {
        alignment: center;
        Rectangle {
            max-width: CustomPalette.preferred-form-width;
            preferred-width: CustomPalette.preferred-form-width;

            VerticalBox {
                alignment: center;
                Rectangle {
    
                    VerticalBox {
                        form := MainMenuForm{}
                    }
                }
            }
        }
    }
}