import { 
    Palette, StyleMetrics, VerticalBox, HorizontalBox, Switch, ListView 
} from "std-widgets.slint";
import { 
    RadioBox, Label, Icons, CustomPalette, Button, StatusIcon, StatusIconData, 
    StatusIconType, ImageSourceSelector, ImageSourceSelectorEntryData
} from "../widgets/widgets.slint";

import { ImageSourceType, PreparedSessionData } from "common.slint";

export component PrepareSession inherits VerticalBox {
    in property<bool> enabled: false;
    in-out property<PreparedSessionData> prepared-session-data;
    in property<[ImageSourceSelectorEntryData]> image-source-selector-datas;

    callback start-session;
    callback open-add-image-source(ImageSourceType);
    callback open-image-source-editor <=> image-source-selector.open-image-source-editor;

    VerticalBox {
        spacing: 0;

        Rectangle {
            height: CustomPalette.preferred-field-height;
            background: Palette.control-background;
            border-top-left-radius: CustomPalette.border;
            border-top-right-radius: CustomPalette.border;
            border-width: CustomPalette.border-width;
            border-color: Palette.background;

            Text {
                text: "Image sources";
            }
        }
        image-source-selector := ImageSourceSelector {
            enabled <=> root.enabled;
            datas <=> root.image-source-selector-datas;
        }
        HorizontalBox {
            spacing: 0;
            padding: 0;

            Rectangle {
                width: CustomPalette.preferred-field-label-width;
                background: Palette.control-background;
                border-width: CustomPalette.border-width;
                border-bottom-left-radius: CustomPalette.border;
                border-color: Palette.background;
    
                Text {
                    width: 100%;
                    x: CustomPalette.border * 2;
                    horizontal-alignment: left;
                    text: "Add Images";
                }
            }

            Button {
                enabled <=> root.enabled;

                border-top-left-radius: 0;
                border-top-right-radius: 0;
                border-bottom-left-radius: 0;

                icon: Icons.folder;
                height: CustomPalette.preferred-field-height;

                clicked => { open-add-image-source(ImageSourceType.Folder); }
            }
        }
        
    }
    
    VerticalBox {
        spacing: 0;

        HorizontalBox {
            spacing: 0;
            padding: 0;
    
            Rectangle {
                width: CustomPalette.preferred-field-label-width;
                background: Palette.control-background;
                border-width: CustomPalette.border-width;
                border-top-left-radius: CustomPalette.border;
                border-color: Palette.background;
    
                Text {
                    width: 100%;
                    x: CustomPalette.border * 2;
                    horizontal-alignment: left;
                    text: "Images";
                }
            }
            RadioBox {
                enabled <=> root.enabled;

                border-top-right: true;
                height: CustomPalette.preferred-field-height;
                selected-value: prepared-session-data.used-image-count;
                datas: [
                    {value: 5, display: "5"},
                    {value: 10, display: "10"},
                    {value: 15, display: "15"},
                    {value: 20, display: "20"},
                    {value: 25, display: "25"},
                ];

                selected-value-changed(value) => {
                    prepared-session-data.used-image-count = value;
                }
            }
        }
        HorizontalBox {
            spacing: 0;
            padding: 0;
    
            Rectangle {
                width: CustomPalette.preferred-field-label-width;
                background: Palette.control-background;
                border-width: CustomPalette.border-width;
                border-bottom-left-radius: CustomPalette.border;
                border-color: Palette.background;
    
                Text {
                    width: 100%;
                    x: CustomPalette.border * 2;
                    horizontal-alignment: left;
                    text: "Duration";
                }
            }
            RadioBox {
                enabled <=> root.enabled;

                border-bottom-right: true;
                height: CustomPalette.preferred-field-height;
                selected-value: prepared-session-data.image-duration;
                datas: [
                    {value: 30, display: "30''"},
                    {value: 60, display: "1'"},
                    {value: 120, display: "2'"},
                    {value: 300, display: "5'"}, 
                    {value: 600, display: "10'"}, 
                ]; 

                selected-value-changed(value) => {
                    prepared-session-data.image-duration = value;
                }
            }
        }
    }
    
    HorizontalBox {
        height: CustomPalette.preferred-field-height;

        Button {
            enabled: root.enabled && prepared-session-data.status.type == StatusIconType.Valid;

            text: "Start (" + prepared-session-data.available-image-count + ")";
            clicked => { start-session(); }
        }

        StatusIcon {
            data: prepared-session-data.status;
        }
    }
}