import { VerticalBox, HorizontalBox, Palette, Slider, StyleMetrics } from "std-widgets.slint";
import { CustomPalette, Icons, Button, Timer } from "../widgets/widgets.slint";
import { PreparedSessionData } from "common.slint";

export component SessionWindow inherits Rectangle {
    in-out property current-image <=> image.source;
    in-out property time-left <=> timer.time-left;

    callback exit-session <=> button_quit.clicked;

    in-out property<bool> expand-menu: false;

    public function prepare-start-session(prepared-session-data: PreparedSessionData) {
        expand-menu = false;
        timer.time-total = prepared-session-data.image-duration;
        time-left = prepared-session-data.image-duration;
    }

    public function show-image(img: image) {
        current-image = img;
    }

    image := Image {}

    Button {
        icon: Icons.more-horizontal-square;
        width: 32px;
        height: 32px;
        x: 8px;
        y: 8px;

        clicked => {
            expand-menu = !expand-menu;
        }
    }

    button-quit := Button {
        visible: expand-menu;
        icon: Icons.square;
        width: 32px;
        height: 32px;
        x: (root.width - self.width) * 0.5;
        y: root.height - self.height - 50px - 50px - 32px;
        text: "Quit";
    }

    timer := Timer {
        x: (root.width - self.width) * 0.5;
        y: root.height - self.height - 50px;
    }
}