import { Palette, HorizontalBox } from "std-widgets.slint";
import { CustomPalette } from "styling.slint";

export component Button inherits Rectangle {
    in property<bool> enabled: true;
    in-out property<image> icon;
    in-out property<string> text;

    in-out property<brush> content-color: Palette.foreground;

    callback clicked;

    min-height: CustomPalette.border;
    min-width: max(32px, layout.min-width);

    border-radius:CustomPalette.border;
    background: Palette.control-background;
    border-width: 1px;
    border-color: Palette.background;
    animate background {
        duration: 50ms;
    }
    
    layout := HorizontalBox {
        alignment: center;
        
        if (root.icon.width > 0 && root.icon.height > 0): Image {
            width: 20px;
            source <=> root.icon;
            image-fit: contain;
            colorize: content-color;
        } 
        if (root.text != ""): Text { 
            color: content-color;
            vertical-alignment: center;
            text: root.text;

            states [
                disabled-pressed when !enabled && touch.pressed: {
                    color: content-color.darker(25%);
                }
                disabled-hover when !enabled && touch.has-hover: {
                    color: content-color;
                }
                disabled when !enabled: {
                    color: content-color.darker(25%);
                }

                normal-pressed when touch.pressed: {
                    color : content-color;
                }
                normal-hover when touch.has-hover: {
                    color : content-color.brighter(25%);
                }
            ]
        }
    }
    touch := TouchArea {
        clicked => {
            if enabled {
                root.clicked();
            }
        }
    }

    states [
        disabled-pressed when !enabled && touch.pressed: {
            background: Palette.background.darker(25%);
        }
        disabled-hover when !enabled && touch.has-hover: {
            background: Palette.alternate-background.darker(25%);
        }
        disabled when !enabled: {
            background: Palette.control-background.darker(25%);
        }

        normal-pressed when touch.pressed: {
            background: Palette.background;
        }
        normal-hover when touch.has-hover: {
            background: Palette.alternate-background;
        }
    ]
}