import { Palette, HorizontalBox, VerticalBox } from "std-widgets.slint";
import { CustomDialog } from "dialog.slint";
import { Button } from "button.slint";
import { Label } from "label.slint";
import { CustomPalette, Icons } from "styling.slint";

component AddFolderDialogForm inherits VerticalBox {
    callback accept;
    callback cancel;

    Rectangle {
        border-radius: CustomPalette.border;

        VerticalBox {
            spacing: 0;
            
            Rectangle {
                height: CustomPalette.preferred-field-height;
                background: Palette.control-background;
                border-top-left-radius: CustomPalette.border;
                border-top-right-radius: CustomPalette.border;
                border-width: CustomPalette.border-width;
                border-color: Palette.background;

                HorizontalBox {
                    Text {
                        text: "Name";
                        vertical-alignment: center;
                    }
                    TextInput {
                        horizontal-alignment: right;
                        vertical-alignment: center;
                        text: "Source Name";
                        color: Palette.control-foreground.darker(25%);
                    }
                    Rectangle {
                        width: CustomPalette.preferred-icon-size;
                    }
                }
            }

            Rectangle {
                background: Palette.control-background;
                border-width: CustomPalette.border-width;
                border-color: Palette.background;

                HorizontalBox {
                    Text {
                        text: "Folder Path";
                        vertical-alignment: center;
                    }
                    Text {
                        horizontal-alignment: right;
                        vertical-alignment: center;
                        text: "/path/to/folder";
                        color: Palette.control-foreground.darker(25%);
                    }
                    Button {
                        icon: Icons.edit;
                        width: CustomPalette.preferred-icon-size;
                        height: CustomPalette.preferred-icon-size;
                        padding: 0;
                    }
                }
            }

            Rectangle {
                background: Palette.control-background;
                border-width: CustomPalette.border-width;
                border-color: Palette.background;

                HorizontalBox {
                    Text {
                        text: "Image Count";
                        vertical-alignment: center;
                    }
                    Text {
                        horizontal-alignment: right;
                        vertical-alignment: center;
                        text: "?";
                        color: Palette.control-foreground.darker(25%);
                    }
                    Rectangle {
                        width: CustomPalette.preferred-icon-size;
                        height: CustomPalette.preferred-icon-size;
                    }
                }
            }

            Rectangle {
                background: Palette.control-background;
                border-bottom-left-radius: CustomPalette.border;
                border-bottom-right-radius: CustomPalette.border;

                HorizontalBox {
                    padding: 0;
                    spacing: 0;

                    Button {
                        height: CustomPalette.preferred-field-height;
                        icon: Icons.plus-circle;
                        border-top-left-radius: 0;
                        border-top-right-radius: 0;
                        border-bottom-right-radius: 0;

                        clicked => { accept(); }
                    }
                    Button {
                        icon: Icons.minus-circle;
                        border-top-left-radius: 0;
                        border-top-right-radius: 0;
                        border-bottom-left-radius: 0;

                        clicked => { cancel(); }
                    }
                }
            }
        }
    }
}

export component AddFolderDialog inherits CustomDialog {

    HorizontalBox {
        alignment: center;
        Rectangle {
            max-width: CustomPalette.preferred-form-width;
            preferred-width: CustomPalette.preferred-form-width;

            VerticalBox {
                alignment: center;
                Rectangle {
                    max-height: 500px;
                    background: Palette.alternate-background;
                    border-color: Palette.background;
                    border-radius: CustomPalette.border;
                    
                    VerticalBox {
                        form := AddFolderDialogForm{
                            accept => { root.accept(); }
                            cancel => { root.cancel(); }
                        }
                    }
                }
            }
        }
    }
}