import { Palette, HorizontalBox, VerticalBox } from "std-widgets.slint";
import { CustomDialog } from "dialog.slint";
import { Button } from "button.slint";
import { Label } from "label.slint";
import { CustomPalette, Icons } from "styling.slint";

export component EditSourceFolderDialog inherits VerticalBox {
    callback accept;
    callback cancel;
    callback open-file-dialog <=> open_file_dialog_button.clicked;

    out property<bool> is-add;

    public function setup-add() {
        is-add = true;
    }

    public function setup-edit() {
        is-add = false;
    }

    Rectangle {
        border-radius: CustomPalette.border;

        VerticalBox {
            spacing: 0;

            Label {
                text: is-add ? "Add Folder" : "Edit Folder";
            }

            // space
            Rectangle {
                height: 4px;
            }
            
            Rectangle {
                height: CustomPalette.preferred-field-height;
                background: Palette.control-background;
                border-top-left-radius: CustomPalette.border;
                border-top-right-radius: CustomPalette.border;
                border-width: CustomPalette.border-width;
                border-color: Palette.background;

                HorizontalBox {
                    Text {
                        text: "Name";
                        vertical-alignment: center;
                    }
                    TextInput {
                        horizontal-alignment: right;
                        vertical-alignment: center;
                        text: "Source Name";
                        color: Palette.control-foreground.darker(25%);
                    }
                    Rectangle {
                        width: CustomPalette.preferred-icon-size;
                    }
                }
            }

            Rectangle {
                background: Palette.control-background;
                border-width: CustomPalette.border-width;
                border-color: Palette.background;

                HorizontalBox {
                    Text {
                        text: "Folder Path";
                        vertical-alignment: center;
                    }
                    Text {
                        horizontal-alignment: right;
                        vertical-alignment: center;
                        text: "/path/to/folder";
                        color: Palette.control-foreground.darker(25%);
                    }
                    open_file_dialog_button := Button {
                        icon: Icons.edit;
                        width: CustomPalette.preferred-icon-size;
                        height: CustomPalette.preferred-icon-size;
                        padding: 0;
                    }
                }
            }

            Rectangle {
                background: Palette.control-background;
                border-width: CustomPalette.border-width;
                border-color: Palette.background;

                HorizontalBox {
                    Text {
                        text: "Image Count";
                        vertical-alignment: center;
                    }
                    Text {
                        horizontal-alignment: right;
                        vertical-alignment: center;
                        text: "?";
                        color: Palette.control-foreground.darker(25%);
                    }
                    Rectangle {
                        width: CustomPalette.preferred-icon-size;
                        height: CustomPalette.preferred-icon-size;
                    }
                }
            }

            Rectangle {
                background: Palette.control-background;
                border-bottom-left-radius: CustomPalette.border;
                border-bottom-right-radius: CustomPalette.border;

                HorizontalBox {
                    padding: 0;
                    spacing: 0;

                    Button {
                        height: CustomPalette.preferred-field-height;
                        icon: Icons.plus-circle;
                        text: is-add ? "Add" : "Save";
                        border-top-left-radius: 0;
                        border-top-right-radius: 0;
                        border-bottom-right-radius: 0;

                        

                        clicked => { accept(); }
                    }
                    Button {
                        icon: Icons.minus-circle;
                        text: is-add ? "Cancel" : "Delete";
                        border-top-left-radius: 0;
                        border-top-right-radius: 0;
                        border-bottom-left-radius: 0;

                        clicked => { cancel(); }
                    }
                }
            }
        }
    }
}