import { Palette, HorizontalBox, VerticalBox } from "std-widgets.slint";
import { Button } from "button.slint";
import { Label } from "label.slint";
import { StatusIconData, StatusIconType } from "status-icon.slint";
import { CustomPalette, Icons } from "styling.slint";

export struct EditSourceFolderData {
    id: string,
    name: string,
    path: string,
    image-count: int,
    status: StatusIconData,
}

export global EditSourceFolderNative {
    callback get-folder-source-data-from-id(string) -> EditSourceFolderData;
    callback is-folder-source-data-from-id-valid(string) -> bool;
    callback add-or-save-folder-source(EditSourceFolderData);
    callback open-folder-dialog-for-source-folder();

    // Test implementations
    get-folder-source-data-from-id(string) => { {
        name: "Test"
    } }
}

export component EditSourceFolder inherits VerticalBox {
    callback on-add-or-save;
    callback cancel;
    callback delete(string);

    /** Native Functions */
    
    /** End Native Functions */

    out property<bool> is-add;
    in-out property<EditSourceFolderData> data;

    public function setup-add() {
        is-add = true;
        data = {
            name: "Unnamed",
            path: "path/to/folder",
            image-count: 0,
            status: {
                type: StatusIconType.Unknown
            },
        };
    }

    public function setup-edit(source-id: string) -> bool {
        data = EditSourceFolderNative.get-folder-source-data-from-id(source-id);
        if (data.id == "") {
            return false;
        }
        
        is-add = false;
        return true;
    }

    Rectangle {
        border-radius: CustomPalette.border;

        VerticalBox {
            spacing: 0;

            Label {
                text: is-add ? "Add Folder" : "Edit Folder";
            }

            // space
            Rectangle {
                height: 4px;
            }
            
            Rectangle {
                height: CustomPalette.preferred-field-height;
                background: Palette.control-background;
                border-top-left-radius: CustomPalette.border;
                border-top-right-radius: CustomPalette.border;
                border-width: CustomPalette.border-width;
                border-color: Palette.background;

                HorizontalBox {
                    Text {
                        text: "Name";
                        vertical-alignment: center;
                    }
                    TextInput {
                        horizontal-alignment: right;
                        vertical-alignment: center;
                        text: data.name;
                        color: Palette.control-foreground.darker(25%);

                        edited => { data.name = self.text; }
                    }
                    Rectangle {
                        width: CustomPalette.preferred-icon-size;
                    }
                }
            }

            Rectangle {
                height: CustomPalette.preferred-field-height;
                background: Palette.control-background;
                border-width: CustomPalette.border-width;
                border-color: Palette.background;

                HorizontalBox {
                    Text {
                        text: "Folder Path";
                        vertical-alignment: center;
                    }
                    Text {
                        horizontal-alignment: right;
                        vertical-alignment: center;
                        text: data.path;
                        color: Palette.control-foreground.darker(25%);
                    }
                    Button {
                        icon: Icons.edit;
                        width: CustomPalette.preferred-icon-size;
                        height: CustomPalette.preferred-icon-size;
                        padding: 0;

                        clicked => {
                            EditSourceFolderNative.open-folder-dialog-for-source-folder();
                        }
                    }
                }
            }

            Rectangle {
                height: CustomPalette.preferred-field-height;
                background: Palette.control-background;
                border-width: CustomPalette.border-width;
                border-color: Palette.background;

                HorizontalBox {
                    Text {
                        text: "Image Count";
                        vertical-alignment: center;
                    }
                    Text {
                        horizontal-alignment: right;
                        vertical-alignment: center;
                        text: data.status.type == StatusIconType.Valid 
                            ? data.image-count 
                            : "?";
                        color: Palette.control-foreground.darker(25%);
                    }
                    Rectangle {
                        width: CustomPalette.preferred-icon-size;
                        height: CustomPalette.preferred-icon-size;
                    }
                }
            }

            if !root.is-add : Rectangle {
                height: CustomPalette.preferred-field-height;
                background: Palette.control-background;
                border-width: CustomPalette.border-width;
                border-color: Palette.background;

                HorizontalBox {
                    padding-right: 0;
                    padding-top: 0;
                    padding-bottom: 0;
                    Text {
                        text: "Delete";
                        vertical-alignment: center;
                    }
                    Button {
                        width: CustomPalette.preferred-field-height * 3;
                        icon: Icons.minus-circle;
                        padding: 0;
                        text: "Delete";
                        content-color: red;
                        border-radius: 0;
                        clicked => { delete(data.id); }
                    }
                }
            }

            Rectangle {
                background: Palette.control-background;
                border-bottom-left-radius: CustomPalette.border;
                border-bottom-right-radius: CustomPalette.border;

                HorizontalBox {
                    padding: 0;
                    spacing: 0;

                    Button {
                        height: CustomPalette.preferred-field-height;
                        icon: Icons.plus-circle;
                        text: is-add ? "Add" : "Save";
                        border-top-left-radius: 0;
                        border-top-right-radius: 0;
                        border-bottom-right-radius: 0;

                        clicked => { 
                            EditSourceFolderNative.add-or-save-folder-source(data);
                            on-add-or-save();
                        }
                    }
                    Button {
                        icon: Icons.minus-circle;
                        text: "Cancel";
                        content-color: Palette.foreground;
                        border-top-left-radius: 0;
                        border-top-right-radius: 0;
                        border-bottom-left-radius: 0;

                        clicked => { cancel(); }
                    }
                }
            }
        }
    }
}