import { Palette, StyleMetrics, Button, HorizontalBox } from "std-widgets.slint";
import { CustomStyleMetrics } from "styling.slint";

enum ItemPlace {
    First,
    Middle,
    Last,
    Alone
}

component RadioButton inherits Rectangle {
    in property<ItemPlace> item-place: ItemPlace.Alone;

    in-out property<bool> selected: false;
    in-out property icon <=> image.source;
    in-out property text <=> text.text;

    callback clicked <=> touch.clicked;

    min-height: CustomStyleMetrics.border;

    border-top-left-radius: item-place == ItemPlace.Alone || item-place == ItemPlace.First 
        ? CustomStyleMetrics.border
        : 0px;
    border-bottom-left-radius: item-place == ItemPlace.Alone || item-place == ItemPlace.First 
        ? CustomStyleMetrics.border
        : 0px;
    border-top-right-radius: item-place == ItemPlace.Alone || item-place == ItemPlace.Last 
        ? CustomStyleMetrics.border
        : 0px;
    border-bottom-right-radius: item-place == ItemPlace.Alone || item-place == ItemPlace.Last 
        ? CustomStyleMetrics.border
        : 0px;

    background: Palette.control-background;
    border-width: 1px;
    border-color: Palette.background;
    
    image := Image {
        width: parent.width * 0.8;
        height: parent.height * 0.8;
        colorize: Palette.foreground;
    } 
    text := Text { 
        color: Palette.foreground;
    }
    touch := TouchArea {}

    states [
        selected-normal when selected: {
            background: Palette.selection-background;
            image.colorize: Palette.selection-foreground;
            text.color : Palette.selection-foreground;
        }
        normal-hover when !selected && touch.has-hover: {
            background: Palette.alternate-background;
            image.colorize: Palette.alternate-foreground;
            text.color : Palette.alternate-foreground;
        }
    ]
}

export component RadioBox inherits HorizontalBox {
    in property<[{value: int, display: string}]> datas;
    in-out property<int> selected-value;
    spacing: 0;

    for data[index] in datas : RadioButton {
        item-place: datas.length < 2 
            ? ItemPlace.Alone
            :   (index == datas.length - 1 
                ? ItemPlace.Last 
                :   (index == 0 
                    ? ItemPlace.First 
                    : ItemPlace.Middle));
                    
        selected: data.value == selected-value;
        text: data.display;
        clicked => {
            root.selected-value = data.value;
        }
    } 
}