import { Palette } from "std-widgets.slint";

// Use cosmic specifics
export global CustomPalette {
    out property<length> border: 8px;
    out property<length> border-width: 1px;
    out property<length> preferred-form-width: 600px;
    out property<length> preferred-field-label-width: 150px;
    out property<length> preferred-field-height: 50px;
    out property<length> preferred-icon-size: 30px;
}

export global Icons {
    out property<image> folder: @image-url("icons/folder.svg");
    out property<image> zip-file: @image-url("icons/document-zip.svg");
    out property<image> edit: @image-url("icons/edit.svg");
    out property<image> check-circle: @image-url("icons/check-circle.svg");
    out property<image> plus-circle: @image-url("icons/plus-circle.svg");
    out property<image> minus-circle: @image-url("icons/minus-circle.svg");
    out property<image> more-horizontal-square: @image-url("icons/more-horizontal-square.svg");
    out property<image> alert-triangle: @image-url("icons/alert-triangle.svg");
}

// From slint-ui
export struct TextStyle {
    font-size: relative-font-size,
    font-weight: int,
}

export global CustomFontSettings {
    out property <int> light-font-weight: 300;
    out property <int> regular-font-weight: 400;
    out property <int> semibold-font-weight: 600;
    out property <TextStyle> body: {
        font-size: 14 * 0.0769rem,
        font-weight: regular-font-weight
    };
    out property <TextStyle> body-strong: {
        font-size: 14 * 0.0769rem,
        font-weight: semibold-font-weight
    };
    out property <TextStyle> title: {
        font-size: 24 * 0.0769rem,
        font-weight: light-font-weight
    };
}