import { Button, VerticalBox, StandardListView, HorizontalBox } from "std-widgets.slint";

component RadioBox inherits HorizontalBox {
    in-out property title <=> title.text;
    height: 50px;
    in property<[{value: int, display: string}]> datas;
    title := Text {
        width: 75px;
        horizontal-alignment: right;
        vertical-alignment: center;
    }
    for data[index] in datas : Button {
        text: data.display;
    } 
}

component CustomDialog inherits Window {
    callback accept;
    callback cancel;
    Rectangle {
        background: white;
    }

    public function show() {
        self.visible = true;
    }
}

component AddFolderDialog inherits CustomDialog {
    VerticalBox {
        HorizontalBox {
            Text {
                text: "Name";
                width: 75px;
                vertical-alignment: center;
                horizontal-alignment: right;
            }
            TextInput {
                vertical-alignment: center;
                horizontal-alignment: center;
                text: "Name of the source";
            }
            Image {
                width: 50px;
                height: 50px;
            }
        }
        HorizontalBox {
            Text {
                text: "Path";
                width: 75px;
                vertical-alignment: center;
                horizontal-alignment: right;
            }
            Text {
                vertical-alignment: center;
                horizontal-alignment: center;
                text: "/path/to/folder";
            }
            Button {
                icon: @image-url("icons/edit.svg");
                width: 50px;
                height: 50px;
            }
        }
        HorizontalBox {
            alignment: space-around;
            padding: 0; 
            HorizontalBox {
                padding: 0;
                Button {
                    icon: @image-url("icons/check-square.svg");
                    width: 50px;
                    height: 50px;
                    clicked => { root.accept(); }
                }
                Image {
                    source: @image-url("icons/alert-triangle.svg");
                    width: 15px;
                    vertical-alignment: center;
                }
            }
            Button {
                icon: @image-url("icons/x-square.svg");
                width: 50px;
                height: 50px;
                clicked => { root.cancel(); }
            }
        }
    }
    
}

component MainMenu inherits VerticalBox {
    callback show-add-folder <=> button_add_folder.clicked;

    padding-left: 5% * root.width;
    padding-right: 5% * root.width;
    padding-top: 5% * root.height;
    padding-bottom: 5% * root.height;

    list := StandardListView {

    }
    HorizontalBox {
        Text {
            width: 75px;
            horizontal-alignment: right;
            vertical-alignment: center;
            text: "Add Source";
        }
        button_add_folder := Button {
            icon: @image-url("icons/folder.svg");
            width: 50px;
            height: 50px;
        }
        button_add_zip := Button {
            icon: @image-url("icons/document-zip.svg");
            width: 50px;
            height: 50px;
        }
    }
    RadioBox {
        title: "Images";
        datas: [
            {value: 5, display: "5"},
            {value: 10, display: "10"},
            {value: 15, display: "15"},
            {value: 20, display: "20"},
            {value: 25, display: "25"},
        ];
    }
    RadioBox {
        title: "Time";
        datas: [
            {value: 30, display: "30''"},
            {value: 60, display: "1'"},
            {value: 120, display: "2'"},
            {value: 180, display: "3'"}, 
            {value: 300, display: "5'"}, 
            {value: 600, display: "10'"}, 
            {value: 600, display: "20'"}, 
        ];
    }
    HorizontalBox {
        Button {
            text: "Start";
        }
    }
}

component ModalDialogLayer inherits Window {
    opacity: 0.5;
    visible: false;
    Rectangle {
        background: black;
    }
    VerticalBox {
        alignment: center;
        x: 5% * root.width;
        width: 90% * root.width;
        min-height: 100px;
        opacity: 1;
        dialog_add_folder := AddFolderDialog { 
            cancel => { close-modal(); } 
        } 
    }

    function close-modal() {
        self.visible = false;

        dialog_add_folder.visible = false;
    }

    public function show-add-folder() {
        self.visible = true; 

        dialog_add_folder.show();
    }
}

export component AppWindow inherits Window {
    title: "Gesture Training";
    MainMenu {
        show-add-folder => { layer_modal.show-add-folder(); }
    } 
    layer_modal := ModalDialogLayer {
        width: root.width;
        height: root.height;
    }
}